#!/bin/bash
#PBS -l nodes=1:ppn=8
#PBS -l vmem=16gb
#PBS -l walltime=10:00:00

export SINGULARITYENV_OMP_NUM_THREADS=7

set -e
set -x

mkdir -p output
chmod -R +w output

time singularity exec -e docker://brainlife/dipy:1.1.1 dipy_fit_dki \
    --force \
    --out_dir output \
    --b0_threshold $(jq -r .b0_threshold config.json) \
    --out_dt_tensor tensors.nii.gz \
    --out_dk_tensor kurtosis.nii.gz \
    $(jq -r .dwi config.json) $(jq -r .bvals config.json) \
    $(jq -r .bvecs config.json) $(jq -r .mask config.json)

echo "done"
